name: Publish package

on:
    release:
        types: [created]
    workflow_dispatch:
    repository_dispatch:

jobs:
    publish-npm:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: 18
                  check-latest: true
                  registry-url: "https://npm.pkg.github.com"
            - uses: pnpm/action-setup@v2
              with:
                  version: 8
                  run_install: |
                      - recursive: true
                        args: [--frozen-lockfile, --strict-peer-dependencies]
            - run: pnpm publish --access=public
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
